CREATE DATABASE IF NOT EXISTS PROJECT;

USE PROJECT;

DROP TABLE IF EXISTS `PROJECT`.`TRAFFIC_ANALYSIS`;
CREATE TABLE IF NOT EXISTS `TRAFFIC_ANALYSIS` (
	`TRAFFIC_INFO_ID` BIGINT(10) NOT NULL AUTO_INCREMENT,
	`SENSORID` BIGINT(10) NOT NULL,
	`SENSORNAME` VARCHAR(100) NOT NULL,
	`VEHICLECOUNT` DOUBLE NULL DEFAULT NULL,
	`ALLOWEDCOUNT` DOUBLE NULL DEFAULT NULL,
	`LOCALITY` VARCHAR(100) NOT NULL,
	`ZIPCODE` VARCHAR(100) NOT NULL,
	`CITY` VARCHAR(100) NOT NULL,
	`TRAFFIC_FLOW` VARCHAR(100) NOT NULL,
	`INSERTED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`UPDATED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`TRAFFIC_INFO_ID`) USING BTREE
)ENGINE=INNODB AUTO_INCREMENT=34 DEFAULT CHARSET=UTF8;

DROP TABLE IF EXISTS `PROJECT`.`TRAFFIC_CUSTOMER_CHALLAN`;
CREATE TABLE IF NOT EXISTS `TRAFFIC_CUSTOMER_CHALLAN` (
	`TRAFFIC_CHALLAN_ID` BIGINT(10) NOT NULL AUTO_INCREMENT,
	`CUSTOMER_ID` BIGINT(10) NOT NULL,
	`CUSTOMER_NAME` VARCHAR(100) NOT NULL,
	`VEHICLENUMBER` VARCHAR(100) NOT NULL,
	`VEHICLETYPE` VARCHAR(100) NOT NULL,
	`LOCALITY` VARCHAR(100) NOT NULL,
	`CITY` VARCHAR(100) NOT NULL,
	`ZIPCODE` VARCHAR(100) NOT NULL,
	`DOB` VARCHAR(100) NOT NULL,
	`CHALLAN_DATE` VARCHAR(100) NULL ,
	`PAID` VARCHAR(100) NOT NULL,
	`AMOUNT` DOUBLE NULL DEFAULT NULL,
	`INSERTED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`UPDATED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`TRAFFIC_CHALLAN_ID`) USING BTREE
)ENGINE=INNODB AUTO_INCREMENT=34 DEFAULT CHARSET=UTF8;

DROP TABLE IF EXISTS `PROJECT`.`TRAFFIC_ACCIDENTS_INFO`;
CREATE TABLE IF NOT EXISTS `TRAFFIC_ACCIDENTS_INFO` (
	`ACCIDENTS_ID` BIGINT(10) NOT NULL AUTO_INCREMENT,
	`BASEACCIDENTSID` BIGINT(10) NOT NULL,
	`ADDRESS_ID` BIGINT(10) NOT NULL,
	`LOCALITY` VARCHAR(100) NOT NULL,
	`CITY` VARCHAR(100) NOT NULL,
	`ZIPCODE` VARCHAR(100) NOT NULL,
	`ACCIDENTDATE` VARCHAR(100) NULL ,
	`ACCIDENTS` BIGINT(10) NULL DEFAULT NULL,
	`INSERTED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`UPDATED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`ACCIDENTS_ID`) USING BTREE
)ENGINE=INNODB AUTO_INCREMENT=34 DEFAULT CHARSET=UTF8;	